### ISSUE TITLE
CustomerTicketClose for OTRS 5

### ISSUE THREAD

**Issue by julianorib** [tuxwerk/OTRS-CustomerTicketClose#2]
Hi.

Do you have plans to develop this addon for OTRS version 5?

Thank you.

**Comment by mck9** [comment]
Hi,
we currently have no plans for an upgrade. Maybe later this year.
.m

**Comment by KoffeinKaio** [comment]
see #3

**Comment by KoffeinKaio** [comment]
@mck9 please dont forget to upload to opar.perl-services.de

**Comment by mck9** [comment]
Sure, have to test it first.
